<a href="https://colab.research.google.com/github/thimotyb/real-world-machine-learning/blob/python3/REST_request_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2022.5.18.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)

In [12]:
# Perform a GET
import requests
api_url = "https://jsonplaceholder.typicode.com/todos"
response = requests.get(api_url)

In [13]:
response

In [14]:
# Payload Json
response.json()

[{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1},
 {'completed': False,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'userId': 1},
 {'completed': False, 'id': 3, 'title': 'fugiat veniam minus', 'userId': 1},
 {'completed': True, 'id': 4, 'title': 'et porro tempora', 'userId': 1},
 {'completed': False,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'userId': 1},
 {'completed': False,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'userId': 1},
 {'completed': False,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'userId': 1},
 {'completed': True,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'userId': 1},
 {'completed': False,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'userId': 1},
 {'completed': True,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'userId': 1},
 {'completed': True,
  'id': 11,
  'title': 'vero rerum temporibus dolor',
  'userId': 1},
 {'completed': True,
  'id': 12,
  'title': 'ipsa repellendus fugit nisi',
  'userId': 1},
 {'completed': False, 'id': 13, 'title': 'et doloremque nulla', 'userId': 1},
 {'completed': True,
  'id': 14,
  'title': 'repellendus sunt dolores architecto voluptatum',
  'userId': 1},
 {'completed': True,
  'id': 15,
  'title': 'ab voluptatum amet voluptas',
  'userId': 1},
 {'completed': True,
  'id': 16,
  'title': 'accusamus eos facilis sint et aut voluptatem',
  'userId': 1},
 {'completed': True,
  'id': 17,
  'title': 'quo laboriosam deleniti aut qui',
  'userId': 1},
 {'completed': False,
  'id': 18,
  'title': 'dolorum est consequatur ea mollitia in culpa',
  'userId': 1},
 {'completed': True,
  'id': 19,
  'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil',
  'userId': 1},
 {'completed': True,
  'id': 20,
  'title': 'ullam nobis libero sapiente ad optio sint',
  'userId': 1},
 {'completed': False,
  'id': 21,
  'title': 'suscipit repellat esse quibusdam voluptatem incidunt',
  'userId': 2},
 {'completed': True,
  'id': 22,
  'title': 'distinctio vitae autem nihil ut molestias quo',
  'userId': 2},
 {'completed': False,
  'id': 23,
  'title': 'et itaque necessitatibus maxime molestiae qui quas velit',
  'userId': 2},
 {'completed': False,
  'id': 24,
  'title': 'adipisci non ad dicta qui amet quaerat doloribus ea',
  'userId': 2},
 {'completed': True,
  'id': 25,
  'title': 'voluptas quo tenetur perspiciatis explicabo natus',
  'userId': 2},
 {'completed': True, 'id': 26, 'title': 'aliquam aut quasi', 'userId': 2},
 {'completed': True,
  'id': 27,
  'title': 'veritatis pariatur delectus',
  'userId': 2},
 {'completed': False,
  'id': 28,
  'title': 'nesciunt totam sit blanditiis sit',
  'userId': 2},
 {'completed': False, 'id': 29, 'title': 'laborum aut in quam', 'userId': 2},
 {'completed': True,
  'id': 30,
  'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis',
  'userId': 2},
 {'completed': False,
  'id': 31,
  'title': 'repudiandae totam in est sint facere fuga',
  'userId': 2},
 {'completed': False,
  'id': 32,
  'title': 'earum doloribus ea doloremque quis',
  'userId': 2},
 {'completed': False, 'id': 33, 'title': 'sint sit aut vero', 'userId': 2},
 {'completed': False,
  'id': 34,
  'title': 'porro aut necessitatibus eaque distinctio',
  'userId': 2},
 {'completed': True,
  'id': 35,
  'title': 'repellendus veritatis molestias dicta incidunt',
  'userId': 2},
 {'completed': True,
  'id': 36,
  'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad',
  'userId': 2},
 {'completed': False, 'id': 37, 'title': 'sunt cum tempora', 'userId': 2},
 {'completed': False, 'id': 38, 'title': 'totam quia non', 'userId': 2},
 {'completed': False,
  'id': 39,
  'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis',
  'userId': 2},
 {'completed': True,
  'id': 40,
  'title': 'totam atque quo nesciunt',
  'userId': 2},
 {'completed': False,
  'id': 41,
  'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit',
  'userId': 3},
 {'completed': False,
  'id': 42,
  'title': 'rerum perferendis error quia ut eveniet',
  'userId': 3},
 {'completed': True,
  'id': 43,
  'title': 'tempore ut sint quis recusandae',
  'userId': 3},
 {'completed': True,
  'id': 44,
  'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis',
  'userId': 3},
 {'completed': False,
  'id': 45,
  'title': 'velit soluta adipisci molestias reiciendis harum',
  'userId': 3},
 {'completed': False,
  'id': 46,
  'title': 'vel voluptatem repellat nihil placeat corporis',
  'userId': 3},
 {'completed': False,
  'id': 47,
  'title': 'nam qui rerum fugiat accusamus',
  'userId': 3},
 {'completed': False,
  'id': 48,
  'title': 'sit reprehenderit omnis quia',
  'userId': 3},
 {'completed': False,
  'id': 49,
  'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et',
  'userId': 3},
 {'completed': True,
  'id': 50,
  'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate',
  'userId': 3},
 {'completed': False,
  'id': 51,
  'title': 'distinctio exercitationem ab doloribus',
  'userId': 3},
 {'completed': False,
  'id': 52,
  'title': 'nesciunt dolorum quis recusandae ad pariatur ratione',
  'userId': 3},
 {'completed': False,
  'id': 53,
  'title': 'qui labore est occaecati recusandae aliquid quam',
  'userId': 3},
 {'completed': True,
  'id': 54,
  'title': 'quis et est ut voluptate quam dolor',
  'userId': 3},
 {'completed': True,
  'id': 55,
  'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione',
  'userId': 3},
 {'completed': True,
  'id': 56,
  'title': 'deleniti ea temporibus enim',
  'userId': 3},
 {'completed': False,
  'id': 57,
  'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia',
  'userId': 3},
 {'completed': False,
  'id': 58,
  'title': 'est dicta totam qui explicabo doloribus qui dignissimos',
  'userId': 3},
 {'completed': False,
  'id': 59,
  'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio',
  'userId': 3},
 {'completed': True,
  'id': 60,
  'title': 'et sequi qui architecto ut adipisci',
  'userId': 3},
 {'completed': True,
  'id': 61,
  'title': 'odit optio omnis qui sunt',
  'userId': 4},
 {'completed': False,
  'id': 62,
  'title': 'et placeat et tempore aspernatur sint numquam',
  'userId': 4},
 {'completed': True,
  'id': 63,
  'title': 'doloremque aut dolores quidem fuga qui nulla',
  'userId': 4},
 {'completed': False,
  'id': 64,
  'title': 'voluptas consequatur qui ut quia magnam nemo esse',
  'userId': 4},
 {'completed': False,
  'id': 65,
  'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni',
  'userId': 4},
 {'completed': False,
  'id': 66,
  'title': 'rerum eum molestias autem voluptatum sit optio',
  'userId': 4},
 {'completed': False,
  'id': 67,
  'title': 'quia voluptatibus voluptatem quos similique maiores repellat',
  'userId': 4},
 {'completed': False,
  'id': 68,
  'title': 'aut id perspiciatis voluptatem iusto',
  'userId': 4},
 {'completed': False,
  'id': 69,
  'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit',
  'userId': 4},
 {'completed': False,
  'id': 70,
  'title': 'ut sequi accusantium et mollitia delectus sunt',
  'userId': 4},
 {'completed': False, 'id': 71, 'title': 'aut velit saepe ullam', 'userId': 4},
 {'completed': False,
  'id': 72,
  'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum',
  'userId': 4},
 {'completed': True,
  'id': 73,
  'title': 'sint amet quia totam corporis qui exercitationem commodi',
  'userId': 4},
 {'completed': False,
  'id': 74,
  'title': 'expedita tempore nobis eveniet laborum maiores',
  'userId': 4},
 {'completed': False,
  'id': 75,
  'title': 'occaecati adipisci est possimus totam',
  'userId': 4},
 {'completed': True, 'id': 76, 'title': 'sequi dolorem sed', 'userId': 4},
 {'completed': False,
  'id': 77,
  'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at',
  'userId': 4},
 {'completed': False,
  'id': 78,
  'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat',
  'userId': 4},
 {'completed': True, 'id': 79, 'title': 'eum ipsa maxime ut', 'userId': 4},
 {'completed': True,
  'id': 80,
  'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur',
  'userId': 4},
 {'completed': True, 'id': 81, 'title': 'suscipit qui totam', 'userId': 5},
 {'completed': False,
  'id': 82,
  'title': 'voluptates eum voluptas et dicta',
  'userId': 5},
 {'completed': True,
  'id': 83,
  'title': 'quidem at rerum quis ex aut sit quam',
  'userId': 5},
 {'completed': False,
  'id': 84,
  'title': 'sunt veritatis ut voluptate',
  'userId': 5},
 {'completed': True, 'id': 85, 'title': 'et quia ad iste a', 'userId': 5},
 {'completed': True,
  'id': 86,
  'title': 'incidunt ut saepe autem',
  'userId': 5},
 {'completed': True,
  'id': 87,
  'title': 'laudantium quae eligendi consequatur quia et vero autem',
  'userId': 5},
 {'completed': False,
  'id': 88,
  'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium',
  'userId': 5},
 {'completed': True, 'id': 89, 'title': 'sequi ut omnis et', 'userId': 5},
 {'completed': True,
  'id': 90,
  'title': 'molestiae nisi accusantium tenetur dolorem et',
  'userId': 5},
 {'completed': True,
  'id': 91,
  'title': 'nulla quis consequatur saepe qui id expedita',
  'userId': 5},
 {'completed': True, 'id': 92, 'title': 'in omnis laboriosam', 'userId': 5},
 {'completed': True,
  'id': 93,
  'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint',
  'userId': 5},
 {'completed': False,
  'id': 94,
  'title': 'facilis modi saepe mollitia',
  'userId': 5},
 {'completed': True,
  'id': 95,
  'title': 'vel nihil et molestiae iusto assumenda nemo quo ut',
  'userId': 5},
 {'completed': False,
  'id': 96,
  'title': 'nobis suscipit ducimus enim asperiores voluptas',
  'userId': 5},
 {'completed': False,
  'id': 97,
  'title': 'dolorum laboriosam eos qui iure aliquam',
  'userId': 5},
 {'completed': True,
  'id': 98,
  'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus',
  'userId': 5},
 {'completed': False,
  'id': 99,
  'title': 'neque voluptates ratione',
  'userId': 5},
 {'completed': False,
  'id': 100,
  'title': 'excepturi a et neque qui expedita vel voluptate',
  'userId': 5},
 {'completed': False,
  'id': 101,
  'title': 'explicabo enim cumque porro aperiam occaecati minima',
  'userId': 6},
 {'completed': False, 'id': 102, 'title': 'sed ab consequatur', 'userId': 6},
 {'completed': False,
  'id': 103,
  'title': 'non sunt delectus illo nulla tenetur enim omnis',
  'userId': 6},
 {'completed': False,
  'id': 104,
  'title': 'excepturi non laudantium quo',
  'userId': 6},
 {'completed': True,
  'id': 105,
  'title': 'totam quia dolorem et illum repellat voluptas optio',
  'userId': 6},
 {'completed': True,
  'id': 106,
  'title': 'ad illo quis voluptatem temporibus',
  'userId': 6},
 {'completed': False,
  'id': 107,
  'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt',
  'userId': 6},
 {'completed': True,
  'id': 108,
  'title': 'a eos eaque nihil et exercitationem incidunt delectus',
  'userId': 6},
 {'completed': True,
  'id': 109,
  'title': 'autem temporibus harum quisquam in culpa',
  'userId': 6},
 {'completed': True, 'id': 110, 'title': 'aut aut ea corporis', 'userId': 6},
 {'completed': False,
  'id': 111,
  'title': 'magni accusantium labore et id quis provident',
  'userId': 6},
 {'completed': False,
  'id': 112,
  'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius',
  'userId': 6},
 {'completed': False,
  'id': 113,
  'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi',
  'userId': 6},
 {'completed': False,
  'id': 114,
  'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae',
  'userId': 6},
 {'completed': False, 'id': 115, 'title': 'sed et ea eum', 'userId': 6},
 {'completed': True,
  'id': 116,
  'title': 'ipsa dolores vel facilis ut',
  'userId': 6},
 {'completed': False,
  'id': 117,
  'title': 'sequi quae est et qui qui eveniet asperiores',
  'userId': 6},
 {'completed': False,
  'id': 118,
  'title': 'quia modi consequatur vero fugiat',
  'userId': 6},
 {'completed': False,
  'id': 119,
  'title': 'corporis ducimus ea perspiciatis iste',
  'userId': 6},
 {'completed': False,
  'id': 120,
  'title': 'dolorem laboriosam vel voluptas et aliquam quasi',
  'userId': 6},
 {'completed': True,
  'id': 121,
  'title': 'inventore aut nihil minima laudantium hic qui omnis',
  'userId': 7},
 {'completed': True,
  'id': 122,
  'title': 'provident aut nobis culpa',
  'userId': 7},
 {'completed': False,
  'id': 123,
  'title': 'esse et quis iste est earum aut impedit',
  'userId': 7},
 {'completed': False, 'id': 124, 'title': 'qui consectetur id', 'userId': 7},
 {'completed': False,
  'id': 125,
  'title': 'aut quasi autem iste tempore illum possimus',
  'userId': 7},
 {'completed': True,
  'id': 126,
  'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe',
  'userId': 7},
 {'completed': True,
  'id': 127,
  'title': 'voluptatem libero consectetur rerum ut',
  'userId': 7},
 {'completed': False,
  'id': 128,
  'title': 'eius omnis est qui voluptatem autem',
  'userId': 7},
 {'completed': False,
  'id': 129,
  'title': 'rerum culpa quis harum',
  'userId': 7},
 {'completed': True,
  'id': 130,
  'title': 'nulla aliquid eveniet harum laborum libero alias ut unde',
  'userId': 7},
 {'completed': False, 'id': 131, 'title': 'qui ea incidunt quis', 'userId': 7},
 {'completed': True,
  'id': 132,
  'title': 'qui molestiae voluptatibus velit iure harum quisquam',
  'userId': 7},
 {'completed': True,
  'id': 133,
  'title': 'et labore eos enim rerum consequatur sunt',
  'userId': 7},
 {'completed': False,
  'id': 134,
  'title': 'molestiae doloribus et laborum quod ea',
  'userId': 7},
 {'completed': False,
  'id': 135,
  'title': 'facere ipsa nam eum voluptates reiciendis vero qui',
  'userId': 7},
 {'completed': False,
  'id': 136,
  'title': 'asperiores illo tempora fuga sed ut quasi adipisci',
  'userId': 7},
 {'completed': False, 'id': 137, 'title': 'qui sit non', 'userId': 7},
 {'completed': True,
  'id': 138,
  'title': 'placeat minima consequatur rem qui ut',
  'userId': 7},
 {'completed': False,
  'id': 139,
  'title': 'consequatur doloribus id possimus voluptas a voluptatem',
  'userId': 7},
 {'completed': True,
  'id': 140,
  'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam',
  'userId': 7},
 {'completed': True,
  'id': 141,
  'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non',
  'userId': 8},
 {'completed': True,
  'id': 142,
  'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut',
  'userId': 8},
 {'completed': False,
  'id': 143,
  'title': 'eum non recusandae cupiditate animi',
  'userId': 8},
 {'completed': False,
  'id': 144,
  'title': 'ut eum exercitationem sint',
  'userId': 8},
 {'completed': False,
  'id': 145,
  'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam',
  'userId': 8},
 {'completed': True,
  'id': 146,
  'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam',
  'userId': 8},
 {'completed': True,
  'id': 147,
  'title': 'eum itaque quod reprehenderit et facilis dolor autem ut',
  'userId': 8},
 {'completed': False,
  'id': 148,
  'title': 'esse quas et quo quasi exercitationem',
  'userId': 8},
 {'completed': False,
  'id': 149,
  'title': 'animi voluptas quod perferendis est',
  'userId': 8},
 {'completed': False,
  'id': 150,
  'title': 'eos amet tempore laudantium fugit a',
  'userId': 8},
 {'completed': True,
  'id': 151,
  'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero',
  'userId': 8},
 {'completed': False,
  'id': 152,
  'title': 'odit eligendi recusandae doloremque cumque non',
  'userId': 8},
 {'completed': False,
  'id': 153,
  'title': 'ea aperiam consequatur qui repellat eos',
  'userId': 8},
 {'completed': True, 'id': 154, 'title': 'rerum non ex sapiente', 'userId': 8},
 {'completed': True,
  'id': 155,
  'title': 'voluptatem nobis consequatur et assumenda magnam',
  'userId': 8},
 {'completed': True,
  'id': 156,
  'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis',
  'userId': 8},
 {'completed': True,
  'id': 157,
  'title': 'dolorem veniam quisquam deserunt repellendus',
  'userId': 8},
 {'completed': True,
  'id': 158,
  'title': 'debitis vitae delectus et harum accusamus aut deleniti a',
  'userId': 8},
 {'completed': True,
  'id': 159,
  'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis',
  'userId': 8},
 {'completed': False,
  'id': 160,
  'title': 'et praesentium aliquam est',
  'userId': 8},
 {'completed': True,
  'id': 161,
  'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa',
  'userId': 9},
 {'completed': True,
  'id': 162,
  'title': 'omnis laboriosam molestias animi sunt dolore',
  'userId': 9},
 {'completed': False,
  'id': 163,
  'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit',
  'userId': 9},
 {'completed': False,
  'id': 164,
  'title': 'reprehenderit quos aut aut consequatur est sed',
  'userId': 9},
 {'completed': False,
  'id': 165,
  'title': 'fugiat perferendis sed aut quidem',
  'userId': 9},
 {'completed': False,
  'id': 166,
  'title': 'quos quo possimus suscipit minima ut',
  'userId': 9},
 {'completed': False,
  'id': 167,
  'title': 'et quis minus quo a asperiores molestiae',
  'userId': 9},
 {'completed': False,
  'id': 168,
  'title': 'recusandae quia qui sunt libero',
  'userId': 9},
 {'completed': True,
  'id': 169,
  'title': 'ea odio perferendis officiis',
  'userId': 9},
 {'completed': False,
  'id': 170,
  'title': 'quisquam aliquam quia doloribus aut',
  'userId': 9},
 {'completed': True,
  'id': 171,
  'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio',
  'userId': 9},
 {'completed': False,
  'id': 172,
  'title': 'et provident amet rerum consectetur et voluptatum',
  'userId': 9},
 {'completed': False,
  'id': 173,
  'title': 'harum ad aperiam quis',
  'userId': 9},
 {'completed': False, 'id': 174, 'title': 'similique aut quo', 'userId': 9},
 {'completed': True,
  'id': 175,
  'title': 'laudantium eius officia perferendis provident perspiciatis asperiores',
  'userId': 9},
 {'completed': False,
  'id': 176,
  'title': 'magni soluta corrupti ut maiores rem quidem',
  'userId': 9},
 {'completed': False,
  'id': 177,
  'title': 'et placeat temporibus voluptas est tempora quos quibusdam',
  'userId': 9},
 {'completed': True,
  'id': 178,
  'title': 'nesciunt itaque commodi tempore',
  'userId': 9},
 {'completed': True,
  'id': 179,
  'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo',
  'userId': 9},
 {'completed': True,
  'id': 180,
  'title': 'debitis nisi et dolorem repellat et',
  'userId': 9},
 {'completed': False,
  'id': 181,
  'title': 'ut cupiditate sequi aliquam fuga maiores',
  'userId': 10},
 {'completed': True,
  'id': 182,
  'title': 'inventore saepe cumque et aut illum enim',
  'userId': 10},
 {'completed': True,
  'id': 183,
  'title': 'omnis nulla eum aliquam distinctio',
  'userId': 10},
 {'completed': False,
  'id': 184,
  'title': 'molestias modi perferendis perspiciatis',
  'userId': 10},
 {'completed': False,
  'id': 185,
  'title': 'voluptates dignissimos sed doloribus animi quaerat aut',
  'userId': 10},
 {'completed': False,
  'id': 186,
  'title': 'explicabo odio est et',
  'userId': 10},
 {'completed': False,
  'id': 187,
  'title': 'consequuntur animi possimus',
  'userId': 10},
 {'completed': True, 'id': 188, 'title': 'vel non beatae est', 'userId': 10},
 {'completed': True,
  'id': 189,
  'title': 'culpa eius et voluptatem et',
  'userId': 10},

In [5]:
response.status_code

200

In [6]:
response.headers

{'Date': 'Fri, 17 Jun 2022 08:58:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'X-Ratelimit-Limit': '1000', 'X-Ratelimit-Remaining': '999', 'X-Ratelimit-Reset': '1655422243', 'Vary': 'Origin, Accept-Encoding', 'Access-Control-Allow-Credentials': 'true', 'Cache-Control': 'max-age=43200', 'Pragma': 'no-cache', 'Expires': '-1', 'X-Content-Type-Options': 'nosniff', 'Etag': 'W/"54-J3JtLgWuXjgj1OZdyAcKAqOaKHo"', 'Via': '1.1 vegur', 'CF-Cache-Status': 'REVALIDATED', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=ja%2FOlHYxdwRC2PzBsnVWS1zjh5r%2BuDqKmI%2BBrvsXtrKP82n7zyqPsZza7ceTXZ%2FFXXo0rcNenH%2BarS%2FiN2gs2IxiJOn4Kzy%2FxI8K33noEj0QGOwlWmyWi2exvXv5783HZg6auuGoTCIL2EUNz3r5"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '71ca95dec9ed59d9-IAD', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}

In [7]:
response.headers['x-ratelimit-remaining']

'999'

In [15]:
response_json = response.json()
for r in response_json:
  print(r['title'])

delectus aut autem
quis ut nam facilis et officia qui
fugiat veniam minus
et porro tempora
laboriosam mollitia et enim quasi adipisci quia provident illum
qui ullam ratione quibusdam voluptatem quia omnis
illo expedita consequatur quia in
quo adipisci enim quam ut ab
molestiae perspiciatis ipsa
illo est ratione doloremque quia maiores aut
vero rerum temporibus dolor
ipsa repellendus fugit nisi
et doloremque nulla
repellendus sunt dolores architecto voluptatum
ab voluptatum amet voluptas
accusamus eos facilis sint et aut voluptatem
quo laboriosam deleniti aut qui
dolorum est consequatur ea mollitia in culpa
molestiae ipsa aut voluptatibus pariatur dolor nihil
ullam nobis libero sapiente ad optio sint
suscipit repellat esse quibusdam voluptatem incidunt
distinctio vitae autem nihil ut molestias quo
et itaque necessitatibus maxime molestiae qui quas velit
adipisci non ad dicta qui amet quaerat doloribus ea
voluptas quo tenetur perspiciatis explicabo natus
aliquam aut quasi
veritatis pariatur delectus
nesciunt totam sit blanditiis sit
laborum aut in quam
nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis
repudiandae totam in est sint facere fuga
earum doloribus ea doloremque quis
sint sit aut vero
porro aut necessitatibus eaque distinctio
repellendus veritatis molestias dicta incidunt
excepturi deleniti adipisci voluptatem et neque optio illum ad
sunt cum tempora
totam quia non
doloremque quibusdam asperiores libero corrupti illum qui omnis
totam atque quo nesciunt
aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit
rerum perferendis error quia ut eveniet
tempore ut sint quis recusandae
cum debitis quis accusamus doloremque ipsa natus sapiente omnis
velit soluta adipisci molestias reiciendis harum
vel voluptatem repellat nihil placeat corporis
nam qui rerum fugiat accusamus
sit reprehenderit omnis quia
ut necessitatibus aut maiores debitis officia blanditiis velit et
cupiditate necessitatibus ullam aut quis dolor voluptate
distinctio exercitationem ab doloribus
nesciunt dolorum quis recusandae ad pariatur ratione
qui labore est occaecati recusandae aliquid quam
quis et est ut voluptate quam dolor
voluptatum omnis minima qui occaecati provident nulla voluptatem ratione
deleniti ea temporibus enim
pariatur et magnam ea doloribus similique voluptatem rerum quia
est dicta totam qui explicabo doloribus qui dignissimos
perspiciatis velit id laborum placeat iusto et aliquam odio
et sequi qui architecto ut adipisci
odit optio omnis qui sunt
et placeat et tempore aspernatur sint numquam
doloremque aut dolores quidem fuga qui nulla
voluptas consequatur qui ut quia magnam nemo esse
fugiat pariatur ratione ut asperiores necessitatibus magni
rerum eum molestias autem voluptatum sit optio
quia voluptatibus voluptatem quos similique maiores repellat
aut id perspiciatis voluptatem iusto
doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit
ut sequi accusantium et mollitia delectus sunt
aut velit saepe ullam
praesentium facilis facere quis harum voluptatibus voluptatem eum
sint amet quia totam corporis qui exercitationem commodi
expedita tempore nobis eveniet laborum maiores
occaecati adipisci est possimus totam
sequi dolorem sed
maiores aut nesciunt delectus exercitationem vel assumenda eligendi at
reiciendis est magnam amet nemo iste recusandae impedit quaerat
eum ipsa maxime ut
tempore molestias dolores rerum sequi voluptates ipsum consequatur
suscipit qui totam
voluptates eum voluptas et dicta
quidem at rerum quis ex aut sit quam
sunt veritatis ut voluptate
et quia ad iste a
incidunt ut saepe autem
laudantium quae eligendi consequatur quia et vero autem
vitae aut excepturi laboriosam sint aliquam et et accusantium
sequi ut omnis et
molestiae nisi accusantium tenetur dolorem et
nulla quis consequatur saepe qui id expedita
in omnis laboriosam
odio iure consequatur molestiae quibusdam necessitatibus quia sint
facilis modi saepe mollitia
vel nihil et molestiae iusto assumenda nemo quo ut
nobis suscipit ducimus enim asperiores voluptas
dolorum laboriosam eos qui iure aliquam
debitis accusantium ut quo facilis nihil quis sapiente necessitatibus
neque voluptates ratione
excepturi a et neque qui expedita vel voluptate
explicabo enim cumque porro aperiam occaecati minima
sed ab consequatur
non sunt delectus illo nulla tenetur enim omnis
excepturi non laudantium quo
totam quia dolorem et illum repellat voluptas optio
ad illo quis voluptatem temporibus
praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt
a eos eaque nihil et exercitationem incidunt delectus
autem temporibus harum quisquam in culpa
aut aut ea corporis
magni accusantium labore et id quis provident
consectetur impedit quisquam qui deserunt non rerum consequuntur eius
quia atque aliquam sunt impedit voluptatum rerum assumenda nisi
cupiditate quos possimus corporis quisquam exercitationem beatae
sed et ea eum
ipsa dolores vel facilis ut
sequi quae est et qui qui eveniet asperiores
quia modi consequatur vero fugiat
corporis ducimus ea perspiciatis iste
dolorem laboriosam vel voluptas et aliquam quasi
inventore aut nihil minima laudantium hic qui omnis
provident aut nobis culpa
esse et quis iste est earum aut impedit
qui consectetur id
aut quasi autem iste tempore illum possimus
ut asperiores perspiciatis veniam ipsum rerum saepe
voluptatem libero consectetur rerum ut
eius omnis est qui voluptatem autem
rerum culpa quis harum
nulla aliquid eveniet harum laborum libero alias ut unde
qui ea incidunt quis
qui molestiae voluptatibus velit iure harum quisquam
et labore eos enim rerum consequatur sunt
molestiae doloribus et laborum quod ea
facere ipsa nam eum voluptates reiciendis vero qui
asperiores illo tempora fuga sed ut quasi adipisci
qui sit non
placeat minima consequatur rem qui ut
consequatur doloribus id possimus voluptas a voluptatem
aut consectetur in blanditiis deserunt quia sed laboriosam
explicabo consectetur debitis voluptates quas quae culpa rerum non
maiores accusantium architecto necessitatibus reiciendis ea aut
eum non recusandae cupiditate animi
ut eum exercitationem sint
beatae qui ullam incidunt voluptatem non nisi aliquam
molestiae suscipit ratione nihil odio libero impedit vero totam
eum itaque quod reprehenderit et facilis dolor autem ut
esse quas et quo quasi exercitationem
animi voluptas quod perferendis est
eos amet tempore laudantium fugit a
accusamus adipisci dicta qui quo ea explicabo sed vero
odit eligendi recusandae doloremque cumque non
ea aperiam consequatur qui repellat eos
rerum non ex sapiente
voluptatem nobis consequatur et assumenda magnam
nam quia quia nulla repellat assumenda quibusdam sit nobis
dolorem veniam quisquam deserunt repellendus
debitis vitae delectus et harum accusamus aut deleniti a
debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis
et praesentium aliquam est
ex hic consequuntur earum omnis alias ut occaecati culpa
omnis laboriosam molestias animi sunt dolore
natus corrupti maxime laudantium et voluptatem laboriosam odit
reprehenderit quos aut aut consequatur est sed
fugiat perferendis sed aut quidem
quos quo possimus suscipit minima ut
et quis minus quo a asperiores molestiae
recusandae quia qui sunt libero
ea odio perferendis officiis
quisquam aliquam quia doloribus aut
fugiat aut voluptatibus corrupti deleniti velit iste odio
et provident amet rerum consectetur et voluptatum
harum ad aperiam quis
similique aut quo
laudantium eius officia perferendis provident perspiciatis asperiores
magni soluta corrupti ut maiores rem quidem
et placeat temporibus voluptas est tempora quos quibusdam
nesciunt itaque commodi tempore
omnis consequuntur cupiditate impedit itaque ipsam quo
debitis nisi et dolorem repellat et
ut cupiditate sequi aliquam fuga maiores
inventore saepe cumque et aut illum enim
omnis nulla eum aliquam distinctio
molestias modi perferendis perspiciatis
voluptates dignissimos sed doloribus animi quaerat aut
explicabo odio est et
consequuntur animi possimus
vel non beatae est
culpa eius et voluptatem et
accusamus sint iusto et voluptatem exercitationem
temporibus atque distinctio omnis eius impedit tempore molestias pariatur
ut quas possimus exercitationem sint voluptates
rerum debitis voluptatem qui eveniet tempora distinctio a
sed ut vero sit molestiae
rerum ex veniam mollitia voluptatibus pariatur
consequuntur aut ut fugit similique
dignissimos quo nobis earum saepe
quis eius est sint explicabo
numquam repellendus a magnam
ipsam aperiam voluptates qui

In [9]:
response_json = response.json()
print(response_json['title'])

fugiat veniam minus

In [10]:
# Import all entities in a dataframe
import pandas as pd
response_all = pd.DataFrame(requests.get('https://jsonplaceholder.typicode.com/todos').json())

In [11]:
response_all.head(6)

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False
5       1   6  qui ullam ratione quibusdam voluptatem quia omnis      False

In [16]:
# POST
todo = {'completed': False, 'id': 1, 'title': 'leggi Guerra e Pace', 'userId': 2}
api_url_post = "https://jsonplaceholder.typicode.com/todos"
response = requests.post(api_url_post, json=todo)

In [17]:
response.json()

{'completed': False, 'id': 201, 'title': 'leggi Guerra e Pace', 'userId': 2}

In [18]:
new_post_id=response.json()['id']
print(new_post_id)

201

In [19]:
# 201 Created
response.status_code

201

In [20]:
# Using a more complex API
us_companies_request_url = 'https://api.usfundamentals.com/v1/companies/xbrl?format=json&token=Tn4Qgyb3hSTS8NAkC44dMw'
us_companies_indicators_url = 'https://api.usfundamentals.com/v1/indicators/xbrl?indicators=Goodwill,NetIncomeLoss,Revenues&token=Tn4Qgyb3hSTS8NAkC44dMw'

In [21]:
import pandas as pd
us_companies = pd.DataFrame(requests.get(us_companies_request_url).json())
us_companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company_id      14999 non-null  object
 1   name_latest     14999 non-null  object
 2   names_previous  3358 non-null   object
dtypes: object(3)
memory usage: 351.7+ KB

In [22]:
us_companies.head(5)

  company_id               name_latest names_previous
0    1000045    Nicholas Financial Inc           None
1    1000180              Sandisk Corp           None
2    1000209  Medallion Financial Corp           None
3    1000228          Henry Schein Inc           None
4    1000229     Core Laboratories N V           None

In [23]:
us_companies_indicators_csv = requests.get(us_companies_indicators_url)
import os, sys
indicators_file = "indicators.csv"
# Open file
with open(indicators_file, mode='w') as f:
  f.write(us_companies_indicators_csv.text)

In [24]:
us_companies_indicators = pd.read_csv(indicators_file)

In [25]:
us_companies_indicators.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22042 entries, 0 to 22041
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    22042 non-null  int64
 1   indicator_id  22042 non-null  object
 2   2010          457 non-null    float64
 3   2011          11779 non-null  float64
 4   2012          12264 non-null  float64
 5   2013          12238 non-null  float64
 6   2014          12326 non-null  float64
 7   2015          11875 non-null  float64
 8   2016          11172 non-null  float64
 9   2017          10868 non-null  float64
 10  2018          10268 non-null  float64
 11  2019          5089 non-null   float64
 12  2020          2641 non-null   float64
dtypes: float64(11), int64(1), object(1)
memory usage: 2.2+ MB

In [26]:
us_companies_indicators.head(5)

,company_id,indicator_id,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,1000045,NetIncomeLoss,NaN,NaN,1.994095e+07,1.670335e+07,1.685589e+07,1.237900e+07,5409000.0,-1098000.0,-3648000.0,3466000.0,NaN
1,1000045,Revenues,NaN,6.816660e+07,8.211045e+07,8.262894e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000180,Goodwill,NaN,1.548990e+08,2.017350e+08,3.181110e+08,8.313280e+08,8.313280e+08,NaN,NaN,NaN,NaN,NaN
3,1000180,NetIncomeLoss,1.300142e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000180,Revenues,4.826807e+09,5.662145e+09,5.052509e+09,6.170003e+09,6.627701e+09,5.564872e+09,NaN,NaN,NaN,NaN,NaN

In [27]:
us_companies_indicators.indicator_id.unique()

array(['NetIncomeLoss', 'Revenues', 'Goodwill'], dtype=object)

In [33]:
us_companies['company_id'] = us_companies['company_id'].astype(int)
company_merge = pd.merge(us_companies, us_companies_indicators, on='company_id')

In [34]:
company_merge.head(5)

,company_id,name_latest,names_previous,indicator_id,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,1000045,Nicholas Financial Inc,None,NetIncomeLoss,NaN,NaN,1.994095e+07,1.670335e+07,1.685589e+07,1.237900e+07,5409000.0,-1098000.0,-3648000.0,3466000.0,NaN
1,1000045,Nicholas Financial Inc,None,Revenues,NaN,6.816660e+07,8.211045e+07,8.262894e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000180,Sandisk Corp,None,Goodwill,NaN,1.548990e+08,2.017350e+08,3.181110e+08,8.313280e+08,8.313280e+08,NaN,NaN,NaN,NaN,NaN
3,1000180,Sandisk Corp,None,NetIncomeLoss,1.300142e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000180,Sandisk Corp,None,Revenues,4.826807e+09,5.662145e+09,5.052509e+09,6.170003e+09,6.627701e+09,5.564872e+09,NaN,NaN,NaN,NaN,NaN